## BASIC EXPLORATORY DATA ANALYSIS
### NOTEBOOK PLANS:
- Read Dataset and check the info, head, isnull, shape, type of columns, value_counts

In [1]:
import pandas as pd

In [6]:
train = pd.read_csv("../data/Train_maskedv2.csv")
test = pd.read_csv("../data/Test_maskedv2.csv")
description = pd.read_csv("../data/variable_descriptions_v2.csv")

### VARIABLE DESCRIPTION

In [11]:
description.head(50)

                  Column                                        Description
0       total_households                Totoal number of households in ward
1      total_individuals                Total number of individuals in ward
2   target_pct_vunerable  Percentage of large households who have to lea...
3                  dw_00  Percentage of dwellings of type: House or bric...
4                  dw_01  Percentage of dwellings of type: Traditional d...
5                  dw_02  Percentage of dwellings of type: Flat or apart...
6                  dw_03  Percentage of dwellings of type: Cluster house...
7                  dw_04  Percentage of dwellings of type: Townhouse (se...
8                  dw_05  Percentage of dwellings of type: Semi-detached...
9                  dw_06  Percentage of dwellings of type: House/flat/ro...
10                 dw_07  Percentage of dwellings of type: Informal dwel...
11                 dw_08  Percentage of dwellings of type: Informal dwel...
12                 dw_09  Percentage of dwellings of type: Room/flatlet ...
13                 dw_10      Percentage of dwellings of type: Caravan/tent
14                 dw_11             Percentage of dwellings of type: Other
15                 dw_12       Percentage of dwellings of type: Unspecified
16                 dw_13    Percentage of dwellings of type: Not applicable
17                psa_00  Percentage listing present school attendance a...
18                psa_01  Percentage listing present school attendance a...
19                psa_02  Percentage listing present school attendance a...
20                psa_03  Percentage listing present school attendance a...
21                psa_04  Percentage listing present school attendance a...
22                stv_00   Percentage of households with Satellite TV:  Yes
23                stv_01    Percentage of households with Satellite TV:  No
24                car_00          Percentage of households with a car:  Yes
25                car_01           Percentage of households with a car:  No
26                lln_00     Percentage listing landline ownership as:  Yes
27                lln_01      Percentage listing landline ownership as:  No
28                lan_00         Percentage listing language as:  Afrikaans
29                lan_01           Percentage listing language as:  English
30                lan_02        Percentage listing language as:  IsiNdebele
31                lan_03          Percentage listing language as:  IsiXhosa
32                lan_04           Percentage listing language as:  IsiZulu
33                lan_05            Percentage listing language as:  Sepedi
34                lan_06           Percentage listing language as:  Sesotho
35                lan_07          Percentage listing language as:  Setswana
36                lan_08     Percentage listing language as:  Sign language
37                lan_09           Percentage listing language as:  SiSwati
38                lan_10         Percentage listing language as:  Tshivenda
39                lan_11          Percentage listing language as:  Xitsonga
40                lan_12             Percentage listing language as:  Other
41                lan_13       Percentage listing language as:  Unspecified
42                lan_14    Percentage listing language as:  Not applicable
43                 pg_00     Percentage in population group:  Black African
44                 pg_01          Percentage in population group:  Coloured
45                 pg_02   Percentage in population group:  Indian or Asian
46                 pg_03             Percentage in population group:  White
47                 pg_04             Percentage in population group:  Other
48                lgt_00          Percentage using electricity for lighting

### TRAIN DATASET

In [3]:
train.shape

(3174, 50)

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3174 entries, 0 to 3173
Data columns (total 50 columns):
ward                    3174 non-null object
total_households        3174 non-null float64
total_individuals       3174 non-null float64
target_pct_vunerable    3174 non-null float64
dw_00                   3174 non-null float64
dw_01                   3174 non-null float64
dw_02                   3174 non-null float64
dw_03                   3174 non-null float64
dw_04                   3174 non-null float64
dw_05                   3174 non-null float64
dw_06                   3174 non-null float64
dw_07                   3174 non-null float64
dw_08                   3174 non-null float64
dw_09                   3174 non-null float64
dw_10                   3174 non-null float64
dw_11                   3174 non-null float64
dw_12                   3174 non-null int64
dw_13                   3174 non-null int64
psa_00                  3174 non-null float64
psa_01                  3174 non-null float64
psa_02                  3174 non-null float64
psa_03                  3174 non-null float64
psa_04                  3174 non-null float64
stv_00                  3174 non-null float64
stv_01                  3174 non-null float64
car_00                  3174 non-null float64
car_01                  3174 non-null float64
lln_00                  3174 non-null float64
lln_01                  3174 non-null float64
lan_00                  3174 non-null float64
lan_01                  3174 non-null float64
lan_02                  3174 non-null float64
lan_03                  3174 non-null float64
lan_04                  3174 non-null float64
lan_05                  3174 non-null float64
lan_06                  3174 non-null float64
lan_07                  3174 non-null float64
lan_08                  3174 non-null float64
lan_09                  3174 non-null float64
lan_10                  3174 non-null float64
lan_11                  3174 non-null float64
lan_12                  3174 non-null float64
lan_13                  3174 non-null int64
lan_14                  3174 non-null float64
pg_00                   3174 non-null float64
pg_01                   3174 non-null float64
pg_02                   3174 non-null float64
pg_03                   3174 non-null float64
pg_04                   3174 non-null float64
lgt_00                  3174 non-null float64
dtypes: float64(46), int64(3), object(1)
memory usage: 1.2+ MB

In [5]:
train.head(-5)

,ward,total_households,total_individuals,target_pct_vunerable,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,...,lan_11,lan_12,lan_13,lan_14,pg_00,pg_01,pg_02,pg_03,pg_04,lgt_00
0,9D9BEUB,13569.97801,39024.03083,1.739801,0.354806,0.004781,0.170498,0.007861,0.006796,0.023082,...,0.001723,0.027796,0,0.026727,0.524666,0.041460,0.394550,0.029031,0.010292,0.599259
1,RERH3XM,13593.88256,32879.94646,1.993381,0.262140,0.002066,0.077669,0.000597,0.000977,0.003759,...,0.041982,0.021312,0,0.015754,0.993900,0.001829,0.000854,0.000586,0.002832,0.699136
2,GJWA3BO,2698.30050,8261.71093,0.038340,0.728101,0.002292,0.051663,0.008209,0.001444,0.005089,...,0.014786,0.005827,0,0.049384,0.990007,0.003582,0.002546,0.003201,0.000663,0.972315
3,GW6VRB7,1965.96698,9069.77694,7.411006,0.613206,0.138127,0.004999,0.002704,0.000000,0.002788,...,0.003087,0.003136,0,0.013562,0.928682,0.004464,0.009854,0.054701,0.002299,0.735333
4,CN9JZJC,1852.07821,9908.84404,8.223907,0.797462,0.120830,0.060677,0.001155,0.001042,0.000508,...,0.000117,0.001471,0,0.000000,0.994072,0.000476,0.004033,0.000704,0.000714,0.646964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164,NXE83T6,3237.36979,12729.78511,16.602085,0.905257,0.020690,0.005435,0.002008,0.000000,0.033181,...,0.010525,0.020554,0,0.000000,0.973582,0.000629,0.000084,0.024599,0.001107,0.898001
3165,J5MNHD7,3433.23746,14456.24775,0.490322,0.917895,0.009003,0.001111,0.000000,0.000000,0.000675,...,0.054485,0.010908,0,0.000000,0.988643,0.006019,0.001363,0.000227,0.003748,0.944319
3166,DXBCMXC,2857.05439,11667.92343,19.679494,0.896275,0.008755,0.006255,0.000395,0.000693,0.000477,...,0.122242,0.007604,0,0.000000,0.997461,0.000283,0.000928,0.000091,0.001236,0.953046
3167,ZVR0O0X,2158.87715,8315.45433,1.244119,0.787286,0.006789,0.001683,0.000000,0.000000,0.000000,...,0.144101,0.004148,0,0.000000,0.997030,0.000261,0.000585,0.000406,0.001718,0.942222
3168,698BBM0,3290.49197,12994.97120,27.698828,0.887546,0.101949,0.000670,0.000940,0.000000,0.002246,...,0.003686,0.012539,0,0.000077,0.999238,0.000000,0.000166,0.000167,0.000428,0.826954

In [12]:
train.isnull().sum()

ward                    0
total_households        0
total_individuals       0
target_pct_vunerable    0
dw_00                   0
dw_01                   0
dw_02                   0
dw_03                   0
dw_04                   0
dw_05                   0
dw_06                   0
dw_07                   0
dw_08                   0
dw_09                   0
dw_10                   0
dw_11                   0
dw_12                   0
dw_13                   0
psa_00                  0
psa_01                  0
psa_02                  0
psa_03                  0
psa_04                  0
stv_00                  0
stv_01                  0
car_00                  0
car_01                  0
lln_00                  0
lln_01                  0
lan_00                  0
lan_01                  0
lan_02                  0
lan_03                  0
lan_04                  0
lan_05                  0
lan_06                  0
lan_07                  0
lan_08                  0
lan_09                  0
lan_10                  0
lan_11                  0
lan_12                  0
lan_13                  0
lan_14                  0
pg_00                   0
pg_01                   0
pg_02                   0
pg_03                   0
pg_04                   0
lgt_00                  0
dtype: int64

In [18]:
train.describe()

,total_households,total_individuals,target_pct_vunerable,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,...,lan_11,lan_12,lan_13,lan_14,pg_00,pg_01,pg_02,pg_03,pg_04,lgt_00
count,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,...,3174.000000,3174.000000,3174.0,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000,3174.000000
mean,3429.319013,12407.679534,10.258947,0.710593,0.097372,0.031894,0.005820,0.008202,0.006047,0.022225,...,0.050327,0.012342,0.0,0.014335,0.863095,0.041924,0.017665,0.073692,0.003624,0.830599
std,3117.342795,9310.300318,12.847192,0.217458,0.188484,0.078634,0.018592,0.029408,0.023772,0.036762,...,0.153493,0.020594,0.0,0.041155,0.248096,0.146524,0.074607,0.169049,0.010378,0.208129
min,1.000000,402.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.011053,0.000000,0.000000,0.000000,0.000000,0.001692
25%,1668.367500,6972.024960,0.429761,0.591480,0.002919,0.002421,0.000000,0.000000,0.000000,0.002676,...,0.000453,0.002477,0.0,0.000000,0.879603,0.000960,0.000848,0.000445,0.000633,0.788085
50%,2263.921720,9217.504670,3.715314,0.766925,0.010649,0.005792,0.000803,0.000603,0.000813,0.008408,...,0.003092,0.006266,0.0,0.000097,0.989811,0.003088,0.001753,0.001206,0.001630,0.909446
75%,3681.155303,13463.543668,17.762604,0.885571,0.074650,0.028085,0.002538,0.002145,0.002921,0.025111,...,0.028330,0.013430,0.0,0.011548,0.995798,0.012419,0.004636,0.039255,0.004025,0.963780
max,39595.195110,91716.746370,100.000000,0.994962,0.931490,0.951806,0.264239,0.392085,0.435912,0.412936,...,0.991674,0.367785,0.0,0.998448,1.000000,0.969519,0.939564,0.940563,0.367842,1.000000

In [22]:
train.columns

Index(['ward', 'total_households', 'total_individuals', 'target_pct_vunerable',
       'dw_00', 'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07',
       'dw_08', 'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00',
       'psa_01', 'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00',
       'car_01', 'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03',
       'lan_04', 'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10',
       'lan_11', 'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02',
       'pg_03', 'pg_04', 'lgt_00'],
      dtype='object')

In [23]:
##  Determine columns we only "0" values

for i in ['total_households', 'total_individuals', 'target_pct_vunerable',
       'dw_00', 'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07',
       'dw_08', 'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00',
       'psa_01', 'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00',
       'car_01', 'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03',
       'lan_04', 'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10',
       'lan_11', 'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02',
       'pg_03', 'pg_04', 'lgt_00']:
    print(i, train[i].mean())

total_households 3429.3190130245716
total_individuals 12407.679533705104
target_pct_vunerable 10.258946922522675
dw_00 0.7105929920727788
dw_01 0.097372260026465
dw_02 0.03189409127945811
dw_03 0.0058203672520479
dw_04 0.008202142283238813
dw_05 0.006047139601764335
dw_06 0.022224737226212984
dw_07 0.038318698336483985
dw_08 0.06371491511783248
dw_09 0.006929873382797731
dw_10 0.0011273772441713916
dw_11 0.007755406136735966
dw_12 0.0
dw_13 0.0
psa_00 0.31265668158286025
psa_01 0.5251678717032141
psa_02 0.0005285530337114039
psa_03 0.03337182866950218
psa_04 0.12827506493667293
stv_00 0.22704092952898586
stv_01 0.7729590704710155
car_00 0.24734632713106475
car_01 0.7526536728689344
lln_00 0.09481466918368003
lln_01 0.9051853308163216
lan_00 0.09916782810712055
lan_01 0.05571304856836805
lan_02 0.027304697486452388
lan_03 0.038956450466288525
lan_04 0.2861848802227472
lan_05 0.12472924123125392
lan_06 0.10101514921455582
lan_07 0.125916585231254
lan_08 0.004469402901386263
lan_09 0.03372759450504096
lan_10 0.025811501505671085
lan_11 0.0503266977091998
lan_12 0.012342173557025875
lan_13 0.0
lan_14 0.01433474928796472
pg_00 0.8630946856171994
pg_01 0.04192414740296164
pg_02 0.017665457112791477
pg_03 0.07369219580182738
pg_04 0.0036235139968494048
lgt_00 0.8305988203367977

### TEST DATA

In [13]:
test.shape

(1102, 49)

In [14]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1102 entries, 0 to 1101
Data columns (total 49 columns):
ward                 1102 non-null object
total_households     1102 non-null float64
total_individuals    1102 non-null float64
dw_00                1102 non-null float64
dw_01                1102 non-null float64
dw_02                1102 non-null float64
dw_03                1102 non-null float64
dw_04                1102 non-null float64
dw_05                1102 non-null float64
dw_06                1102 non-null float64
dw_07                1102 non-null float64
dw_08                1102 non-null float64
dw_09                1102 non-null float64
dw_10                1102 non-null float64
dw_11                1102 non-null float64
dw_12                1102 non-null int64
dw_13                1102 non-null int64
psa_00               1102 non-null float64
psa_01               1102 non-null float64
psa_02               1102 non-null float64
psa_03               1102 non-null float64
psa_04               1102 non-null float64
stv_00               1102 non-null float64
stv_01               1102 non-null float64
car_00               1102 non-null float64
car_01               1102 non-null float64
lln_00               1102 non-null float64
lln_01               1102 non-null float64
lan_00               1102 non-null float64
lan_01               1102 non-null float64
lan_02               1102 non-null float64
lan_03               1102 non-null float64
lan_04               1102 non-null float64
lan_05               1102 non-null float64
lan_06               1102 non-null float64
lan_07               1102 non-null float64
lan_08               1102 non-null float64
lan_09               1102 non-null float64
lan_10               1102 non-null float64
lan_11               1102 non-null float64
lan_12               1102 non-null float64
lan_13               1102 non-null int64
lan_14               1102 non-null float64
pg_00                1102 non-null float64
pg_01                1102 non-null float64
pg_02                1102 non-null float64
pg_03                1102 non-null float64
pg_04                1102 non-null float64
lgt_00               1102 non-null float64
dtypes: float64(45), int64(3), object(1)
memory usage: 422.0+ KB

In [16]:
test.head(-5)

,ward,total_households,total_individuals,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,...,lan_11,lan_12,lan_13,lan_14,pg_00,pg_01,pg_02,pg_03,pg_04,lgt_00
0,00A93O0,2514.04172,8037.06199,0.671962,0.061074,0.101516,0.006891,0.021287,0.015615,0.035974,...,0.000420,0.011485,0,0.063705,0.979272,0.009926,0.003224,0.002697,0.004882,0.521007
1,01V40KO,1829.71944,7494.86917,0.542857,0.390850,0.039623,0.000000,0.000000,0.000000,0.002633,...,0.000000,0.000160,0,0.000000,0.998938,0.000296,0.000301,0.000305,0.000160,0.693716
2,01ZHVW0,1721.99009,5847.43254,0.968071,0.003525,0.001431,0.000000,0.000000,0.000000,0.018546,...,0.000631,0.006504,0,0.000171,0.955895,0.012170,0.000000,0.030012,0.001923,0.933954
3,028YQJX,12388.02257,52211.66859,0.397274,0.004734,0.001068,0.000279,0.000799,0.197760,0.005227,...,0.000593,0.008330,0,0.000000,0.293629,0.694779,0.003238,0.000628,0.007726,0.921470
4,02G8W11,1754.25716,4266.57609,0.815197,0.016697,0.078571,0.008975,0.047882,0.015398,0.007264,...,0.000234,0.016846,0,0.178598,0.110861,0.054114,0.006062,0.823495,0.005470,0.996227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1092,ZQFMQVU,644.97611,4017.80431,0.191619,0.771899,0.010394,0.003008,0.000000,0.000000,0.012174,...,0.000284,0.000000,0,0.000000,0.994629,0.002823,0.001420,0.000851,0.000276,0.828513
1093,ZRAHMG2,1833.93993,5994.88742,0.919984,0.000679,0.006720,0.002507,0.006216,0.001819,0.003123,...,0.000000,0.009470,0,0.046873,0.095230,0.736272,0.003240,0.160908,0.004349,0.967653
1094,ZS0Z900,1422.63001,6437.04490,0.165573,0.814350,0.011429,0.001687,0.000965,0.000000,0.003060,...,0.000000,0.000373,0,0.000000,0.997117,0.000000,0.001791,0.000719,0.000373,0.829101
1095,ZSNE8SY,2156.98920,6488.53855,0.731797,0.028643,0.003449,0.002388,0.000000,0.000000,0.001814,...,0.001078,0.009212,0,0.002620,0.763882,0.129269,0.001733,0.099583,0.005533,0.798787
1096,ZUX503E,2404.99869,8472.23564,0.889577,0.008945,0.030178,0.000515,0.001567,0.035238,0.009063,...,0.000140,0.000833,0,0.052052,0.046030,0.749280,0.006059,0.196710,0.001920,0.918731

In [15]:
test.isnull().sum()

ward                 0
total_households     0
total_individuals    0
dw_00                0
dw_01                0
dw_02                0
dw_03                0
dw_04                0
dw_05                0
dw_06                0
dw_07                0
dw_08                0
dw_09                0
dw_10                0
dw_11                0
dw_12                0
dw_13                0
psa_00               0
psa_01               0
psa_02               0
psa_03               0
psa_04               0
stv_00               0
stv_01               0
car_00               0
car_01               0
lln_00               0
lln_01               0
lan_00               0
lan_01               0
lan_02               0
lan_03               0
lan_04               0
lan_05               0
lan_06               0
lan_07               0
lan_08               0
lan_09               0
lan_10               0
lan_11               0
lan_12               0
lan_13               0
lan_14               0
pg_00                0
pg_01                0
pg_02                0
pg_03                0
pg_04                0
lgt_00               0
dtype: int64

In [17]:
test.describe()

,total_households,total_individuals,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,dw_07,...,lan_11,lan_12,lan_13,lan_14,pg_00,pg_01,pg_02,pg_03,pg_04,lgt_00
count,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,...,1102.000000,1102.000000,1102.0,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000,1102.000000
mean,2954.164036,11238.464051,0.554544,0.237620,0.045786,0.003852,0.005205,0.026109,0.026799,0.030418,...,0.000697,0.008765,0.0,0.022219,0.672871,0.228805,0.004585,0.087391,0.006347,0.791468
std,2668.061890,8912.095777,0.282261,0.314265,0.078767,0.009472,0.015252,0.067398,0.040966,0.049703,...,0.001423,0.014138,0.0,0.060707,0.395152,0.324664,0.013210,0.184184,0.010378,0.258186
min,106.083320,359.881550,0.005075,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.011043,0.000000,0.000000,0.000000,0.000000,0.001048
25%,1598.110323,6445.408132,0.309676,0.003207,0.006650,0.000000,0.000000,0.000434,0.005224,0.002588,...,0.000000,0.001222,0.0,0.000000,0.202813,0.001221,0.000713,0.000548,0.000717,0.750859
50%,1964.204415,8083.349425,0.611551,0.015616,0.019158,0.000938,0.000726,0.002011,0.012352,0.009622,...,0.000245,0.004117,0.0,0.000934,0.970641,0.012663,0.001593,0.001889,0.003037,0.888062
75%,2903.223162,11523.767912,0.801064,0.506504,0.049493,0.002594,0.002615,0.015702,0.028745,0.035531,...,0.000734,0.009616,0.0,0.018276,0.995667,0.483053,0.004150,0.075370,0.007862,0.962184
max,20214.332000,64511.520420,0.982412,0.985465,0.760766,0.110322,0.222271,0.742617,0.418048,0.440729,...,0.014121,0.125735,0.0,0.925600,0.999697,0.982037,0.281499,0.925508,0.185216,1.000000

In [25]:
## Determine columns we only "0" values

for i in ['total_households', 'total_individuals',
       'dw_00', 'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07',
       'dw_08', 'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00',
       'psa_01', 'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00',
       'car_01', 'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03',
       'lan_04', 'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10',
       'lan_11', 'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02',
       'pg_03', 'pg_04', 'lgt_00']:
    print(i, test[i].mean())

total_households 2954.164036088931
total_individuals 11238.46405093466
dw_00 0.5545435543502727
dw_01 0.23761963898185112
dw_02 0.04578607601270424
dw_03 0.0038522727931034483
dw_04 0.005205047486388379
dw_05 0.02610894402450092
dw_06 0.026798509735934662
dw_07 0.030418442829401076
dw_08 0.054733165721415615
dw_09 0.005166588362976412
dw_10 0.001265927946460979
dw_11 0.008501831689655176
dw_12 0.0
dw_13 0.0
psa_00 0.30187379657440994
psa_01 0.5266238367849362
psa_02 0.0004758530862068964
psa_03 0.03969434059709625
psa_04 0.13133217303539024
stv_00 0.1951927005081668
stv_01 0.8048072994918334
car_00 0.2495700445998184
car_01 0.7504299554001815
lln_00 0.1456354193865697
lln_01 0.8543645806134313
lan_00 0.2704682149509986
lan_01 0.07140984461161522
lan_02 0.002117943562613429
lan_03 0.5869539425671512
lan_04 0.004287128249546285
lan_05 0.0018340432096188776
lan_06 0.022157622592558993
lan_07 0.0026983384836660597
lan_08 0.005430819643375684
lan_09 0.00036109054174228645
lan_10 0.0005987805889292194
lan_11 0.0006974750580762252
lan_12 0.008765418878402906
lan_13 0.0
lan_14 0.022219336928312163
pg_00 0.6728714697196012
pg_01 0.2288048612776768
pg_02 0.004585468352087115
pg_03 0.08739148305172414
pg_04 0.00634671762250454
lgt_00 0.7914678105254086

### CONCLUSION:
- All the columns are numerical
- There is no missing entry in the data
- Columns "lan_13", "dw_12" and "dw_13" seems to be redundant and should be dropped